# Generated by Django 2.1.7 on 2019-04-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0003_dialogue_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogue',
            name='mode',
            field=models.TextField(default='en', max_length=7),
        ),
    ]
