# Generated by Django 2.1.7 on 2019-04-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0004_dialogue_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogue',
            name='mode',
            field=models.TextField(max_length=7),
        ),
    ]
