<<<<<<< HEAD
# Generated by Django 2.1.7 on 2019-04-29 14:51
=======
# Generated by Django 2.1.7 on 2019-04-29 15:25
>>>>>>> 99898fa77aba9e80a21ec4b93dee162aff1ce39e

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0005_auto_20190427_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogue',
            name='user_id',
<<<<<<< HEAD
            field=models.TextField(null=True),
=======
            field=models.TextField(max_length=10, null=True),
>>>>>>> 99898fa77aba9e80a21ec4b93dee162aff1ce39e
        ),
    ]
