# Generated by Django 2.1.7 on 2019-04-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0005_auto_20190427_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogue',
            name='user_id',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
